#!/bin/sh

# Make the archive directory if it doesn't already exist
mkdir -p "archive"

# Make directory "new", empty
if [ -d "new" ]; then
    rm -r "new"
fi
mkdir "new"

# Iterate through the ork files in the current directory; unzip to subdirs in new
for file in *.ork; do
    stem="${file%.*}"
    dest="new/${stem}"
    mkdir ${dest}
    unzip -o -qq ${file} -d ${dest}
done

# see if "new" and "archive" match
diff -rq "archive" "new" > /dev/null
if [ $? == 1 ]; then
    # not a match; replace the archive dir with "new"; exit failing
    rm -r archive
    mv "new" "archive"
    echo "Changes applied to local archive. You may now commit your changes (make sure the archived files are included in the new commit)"
    exit 1
else
    # match; allow user to commit
    rm -r "new"
    exit 0
fi